#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

eval "$(conda shell.bash hook)"
conda activate glip

export CUDA_HOME="${CUDA_HOME:-/usr/local/cuda}"
export PATH="${CUDA_HOME}/bin:${PATH}"
export HF_ENDPOINT="${HF_ENDPOINT:-https://hf-mirror.com}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export TORCH_DISTRIBUTED_DEBUG="${TORCH_DISTRIBUTED_DEBUG:-DETAIL}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-8}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:64}"

NPROC_PER_NODE="${NPROC_PER_NODE:-8}"
GLOBAL_BATCH="${GLOBAL_BATCH:-8}"
TEST_BATCH="${TEST_BATCH:-8}"
NUM_WORKERS="${NUM_WORKERS:-}"
OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/OUTPUT/tct_ngc_v2_base_dev30_glip_tiny_goldg_ccsbu}"
PRETRAIN_WEIGHT="${PRETRAIN_WEIGHT:-MODEL/glip_tiny_model_o365_goldg_cc_sbu.pth}"
TRAIN_MIN_SIZES="${TRAIN_MIN_SIZES:-}"
TRAIN_MAX_SIZE="${TRAIN_MAX_SIZE:-}"

EXTRA_OPTS=()
if [[ -n "${TRAIN_MIN_SIZES}" ]]; then
  EXTRA_OPTS+=(AUGMENT.MULT_MIN_SIZE_TRAIN "${TRAIN_MIN_SIZES}")
fi
if [[ -n "${TRAIN_MAX_SIZE}" ]]; then
  EXTRA_OPTS+=(INPUT.MAX_SIZE_TRAIN "${TRAIN_MAX_SIZE}" INPUT.MAX_SIZE_TEST "${TRAIN_MAX_SIZE}")
fi
if [[ -n "${NUM_WORKERS}" ]]; then
  EXTRA_OPTS+=(DATALOADER.NUM_WORKERS "${NUM_WORKERS}")
fi

torchrun --nproc_per_node="${NPROC_PER_NODE}" tools/finetune.py \
  --config-file configs/pretrain/glip_Swin_T_O365.yaml \
  --ft-tasks configs/tct_ngc/tct_ngc_v2_base.yaml \
  --skip-test \
  MODEL.WEIGHT "${PRETRAIN_WEIGHT}" \
  OUTPUT_DIR "${OUTPUT_DIR}" \
  SOLVER.USE_AMP True \
  SOLVER.IMS_PER_BATCH "${GLOBAL_BATCH}" \
  TEST.IMS_PER_BATCH "${TEST_BATCH}" \
  TEST.EVAL_TASK detection \
  TEST.DURING_TRAINING True \
  DATASETS.TRAIN_DATASETNAME_SUFFIX _grounding \
  DATASETS.USE_OVERRIDE_CATEGORY True \
  DATASETS.DISABLE_SHUFFLE True \
  MODEL.BACKBONE.FREEZE_CONV_BODY_AT 2 \
  MODEL.BACKBONE.USE_CHECKPOINT True \
  MODEL.DYHEAD.USE_CHECKPOINT True \
  MODEL.LANGUAGE_BACKBONE.USE_CHECKPOINT True \
  SOLVER.FIND_UNUSED_PARAMETERS False \
  SOLVER.TEST_WITH_INFERENCE True \
  SOLVER.USE_AUTOSTEP True \
  SOLVER.STEP_PATIENCE 2 \
  SOLVER.AUTO_TERMINATE_PATIENCE 4 \
  SOLVER.CHECKPOINT_PER_EPOCH 1.0 \
  SOLVER.MODEL_EMA 0.0 \
  SOLVER.TUNING_HIGHLEVEL_OVERRIDE full \
  SOLVER.WEIGHT_DECAY 0.05 \
  SOLVER.SEED 10 \
  DATASETS.SHUFFLE_SEED 3 \
  "${EXTRA_OPTS[@]}"
